### ISSUE TITLE
Transfer Sodium.jl

### ISSUE THREAD

**Issue by Gnimuc** [christopher-dG/SodiumSeal.jl#1]
Hi, would you like to maintain [Sodium.jl](https://github.com/Gnimuc/Sodium.jl)? If so, I'll transfer it to you.

**Comment by christopher-dG** [comment]
Well... not really. :upside_down_face: 

I don't anticipate having a use for the full library and I don't really know how Clang.jl works so I don't think I'm the right person.

**Comment by Gnimuc** [comment]
OK, I'll temporarily maintain it myself. I actually never got a chance to use this lib. The main purpose of building such a library is to reproduce macro handling bugs in Clang.jl. 😂
